version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "14:00"
      timezone: "Asia/Tokyo"
    versioning-strategy: increase
    open-pull-requests-limit: 5
